### ISSUE TITLE
Portal names sorting

### ISSUE THREAD

**Issue by Balzhur** [sweetgiorni/AnyPortal#5]
Could you please implement configurable portal names sorting in the drop-down list?
I could think of three useful variants: Alphabetic, Distance, Last Visited. I, personally, need only alphabetic one - to check portals one by one trying to find my missing boat :)

**Comment by sweetgiorni** [comment]
1.0.4 now has alphabetic sorting. Between the three I think that's the most useful because the order should stay consistent as you play. 

I _could_ add configurable sorting, but... I dunno. I don't feel like that's super useful. I just added another button in 1.0.4 and now the configuration UI is starting to look a little busy. I think I'll leave it alone for now, but if more people ask about this I'll take a stab at it.
